### ISSUE TITLE
install on linux

### ISSUE THREAD

**Issue by redfoz12** [TermuxHackz/X-osint#15]
Traceback (most recent call last):
  File "/usr/local/bin/xosint", line 22, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'
After im install got an error
using kali linux

**Comment by TermuxHackz** [comment]
Hello @redfoz12 , thanks for opening an issue via GitHub, open a new terminal and run *pip install imdbpy* and then run xosint again. That should fix your error. And if it doesn't still work try using *pip install IMDbPY* Thank you

**Comment by redfoz12** [comment]
i got another error
Traceback (most recent call last):
  File "/usr/local/bin/xosint", line 29, in <module>
    import piexif
ModuleNotFoundError: No module named 'piexif'

**Comment by TermuxHackz** [comment]
@redfoz12 , sorrry about the issue you are facing, I'll quickly rectify the issue in a couple of seconds and you can be sure to update the X-osint at 9:40am BST

**Comment by TermuxHackz** [comment]
@redfoz12 , I just went through the code and it still works, however u are getting the error saying piexif module is missing, I suggest you kindly run the setup file for xosint again or manually type <code>**pip install piexif**</code> in a new terminal and run xosint again, thank you!

**Comment by redfoz12** [comment]
yeah i just tried install all package with `sudo pip3 piexif` and all smooth right now thanl you
