### ISSUE TITLE
ModuleNotFoundError: No module named 'piexif'

### ISSUE THREAD

**Issue by leo12757** [TermuxHackz/X-osint#20]
Installing X-osint on a freshly installed Kali system, when executing it shows this error, any help?
Thanks.
![未命名](https://github.com/TermuxHackz/X-osint/assets/3197638/8d310506-e977-47f5-a1a1-690cde6ec47a)

**Comment by GitHuugo** [comment]
I got the same error, I had to install several modules (including piexif) manually by using:
` sudo pip install piexif
`

**Comment by TermuxHackz** [comment]
Hello thanks for the issue brought to my attention, I will make a fix for it soon and then you can update and try again 
However u can try running , <code>pip3 install piexif</code>

**Comment by leo12757** [comment]
Thanks for the reply, the problem still exists...
![未命名2](https://github.com/TermuxHackz/X-osint/assets/3197638/cbd921dc-b3b4-4538-b173-efa7f2ae5af7)

**Comment by Xerataw** [comment]
I have the same issue.. Even after the pip3 install piexif

**Comment by TermuxHackz** [comment]
Hello @Xerataw , thanks for notifying me on the issue you are experiencing when using xosint, in working on removing the module from xosint but I will be forced to remove the feature being used by the module.

**Comment by laurenzm** [comment]
Hello,
With the last python3 version, some modules must be installed by the packet-manager of the distro.
Just try to use python virtual environment :
python3 -m venv X-osint_venv
source X-osint_venv/bin/activate
./setup.sh
## I don't know why, but google not correctly install. Then do this.
pip install google
## for execution :
python xosint

**Comment by TermuxHackz** [comment]
@laurenzm , @Xerataw , @leo12757 , Newer version X-osint 2.2 has been released, all bugs fixed and new features added, while some still in beta
