### ISSUE TITLE
No module named 'piexif' and yes, i already tested everything

### ISSUE THREAD

**Issue by oasn** [TermuxHackz/X-osint#22]
Hello,
as the title say, i tried already everything what typed in issues in github. i uninstalled and installed it again, did the setup process twice, but nothing works. pip install piexif, no. it don't work. yes, it installs the module, but it will not be found on xosint. can someone please help. 
thank you.

best regads,
oasn
![Bild_2023-08-28_031240870](https://github.com/TermuxHackz/X-osint/assets/120338660/4d1584bd-aa98-4f52-bafa-cd4defb692a6)

**Comment by TermuxHackz** [comment]
Hi there @oasn , thanks for letting me know about the issue you are currently you experiencing with Xosint I’ll review my code and rectify the issues in about 72hrs from now and then you can run an update by removing your current Xosint and installing the updated one. Thank you

**Comment by DreherAdam** [comment]
Just wanted to see if there was an update on this, im having the same issue as well. thank you!

**Comment by Jochem-Groeneweg** [comment]
Try: sudo -E xosint

**Comment by DreherAdam** [comment]
> Try: sudo -E xosint

That works!

**Comment by marwan2elsayyad** [comment]
try: xosint

**Comment by s-wiz** [comment]
I am facing the same issue
I tried every solution given above but none working for me
@TermuxHackz

**Comment by TermuxHackz** [comment]
@s-wiz New update to be released soon bugs should be fixed

**Comment by Jochem-Groeneweg** [comment]
@TermuxHackz Thanks! Absolutely love this repo!

**Comment by TermuxHackz** [comment]
@Jochem-Groeneweg Thank you, a newer version would be released today by 4PM BST

**Comment by TermuxHackz** [comment]
@Jochem-Groeneweg new update has been released, kindly test and provide feedback for any found bug
