### ISSUE TITLE
Dont run correctly 

### ISSUE THREAD

**Issue by zhadow01** [TermuxHackz/X-osint#28]
Traceback (most recent call last):
  File "/data/data/com.termux/files/home/Moriarty-Project/X-osint/xosint", line 37, in <module>
    import folium
ModuleNotFoundError: No module named 'folium'

**Comment by MarsVenx01** [comment]
Hello there thanks for contacting me kindly read the FAQS stated on the README for how to fix this particular issue regarding X-osint, thank youOn 2 Oct 2023, at 07:14, zhadow01 ***@***.***> wrote:﻿
Traceback (most recent call last):
File "/data/data/com.termux/files/home/Moriarty-Project/X-osint/xosint", line 37, in 
import folium
ModuleNotFoundError: No module named 'folium'

**Comment by 6oname** [comment]
![Screenshot_2024-07-23-23-28-44-783_com termux](https://github.com/user-attachments/assets/a58f9c92-fc8a-465f-8a59-551fe261fcc8)
![Screenshot_2024-07-23-23-30-14-251_com termux](https://github.com/user-attachments/assets/aefc2c2f-1f2a-4e93-abeb-d8506466903f)
Guys, help me what should I do?
