### ISSUE TITLE
No such file: source X-osint_venv/bin/activate ./setup.sh (Termux)

### ISSUE THREAD

**Issue by CazerraColt18** [TermuxHackz/X-osint#32]
![IMG_20231231_204907](https://github.com/TermuxHackz/X-osint/assets/91856380/b8f36efb-0e9e-441c-b0dc-4416b3e58ba2)
Because it doesn't work for normal installation, I used the second method. And it happens like in the picture.

**Comment by TermuxHackz** [comment]
@CazerraColt18 Kindly refer to the README file on creating a python virtual environment for running X-osint
