### ISSUE TITLE
Options not opening

### ISSUE THREAD

**Issue by MDHaarith** [TermuxHackz/X-osint#34]
The gmail information and phone number information aren't coming why??

**Comment by MarsVenx01** [comment]
Hi thanks for your message, there are certain issues with it as you would notice there’s a warning which says “not working for now “On 9 Jan 2024, at 01:12, MDHaarith ***@***.***> wrote:﻿
The gmail information and phone number information aren't coming why??

**Comment by mr-robot-EH** [comment]
When will you return to work? (Gmail/number)

**Comment by TermuxHackz** [comment]
@mr-robot-EH very soon but however, getting the location from the number cannot be done anymore
