### ISSUE TITLE
xosint Traceback (most recent call last):   File "/data/data/com.termux/files/usr/bin/xosint", line 37, in <module>     import folium ModuleNotFoundError: No module named 'folium'

### ISSUE THREAD

**Issue by Arientina1** [TermuxHackz/X-osint#39]
How to install folium plis

**Comment by TermuxHackz** [comment]
Hello there @Arientina1 read the FAQs [here](https://github.com/TermuxHackz/X-osint#faqs) on how to install folium for your terminal 
Thank you
