### ISSUE TITLE
Consider adding free integration to Hudson Rock cybercrime intelligence API

### ISSUE THREAD

**Issue by hudsonrock-partnerships** [TermuxHackz/X-osint#42]
Hudson Rock's free API allows one to check if an email address or domain was compromised in a global Infostealer attack.

Consider adding our complimentary data to your enrichment stack and bring more useful insights to your community. The endpoints we currently have for these kinds of integrations are - 

Email search:  https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-email?email=manvirdi2000@gmail.com

Domain search:  https://cavalier.hudsonrock.com/api/json/v2/osint-tools/search-by-domain?domain=tesla.com&source=telegram

To better understand how these integrations look like, please check out our free Telegram Bot and initiate an email search or a domain search: [www.t.me/hudsonrockbot](http://www.t.me/hudsonrockbot) 

Your consideration of integrating our data would be greatly appreciated!

**Comment by TermuxHackz** [comment]
Hello @hudsonrock-partnerships ,would love to say thank you for the consent of using your free API would definitely implement it in the next update, would love to discuss more.

**Comment by hudsonrock-partnerships** [comment]
Feel free to reach out to leonid@hudsonrock.com to talk about additional details.

**Comment by TermuxHackz** [comment]
@hudsonrock-partnerships I have sent some propositions via the email waiting for a response
