### ISSUE TITLE
Error while cloning

### ISSUE THREAD

**Issue by Swiftness48** [TermuxHackz/X-osint#43]
~ $ git clone https://github.com/TermuxHackz/X-osint
Cloning into 'X-osint'...
remote: Enumerating objects: 473, done.
remote: Counting objects: 100% (150/150), done.
remote: Compressing objects: 100% (111/111), done.
error: RPC failed; curl 92 HTTP/2 stream 5 was not closed cleanly: CANCEL (err 8)
error: 63219 bytes of body are still expected
fetch-pack: unexpected disconnect while reading sideband packet
fatal: early EOF
fatal: fetch-pack: invalid index-pack output
~ $ ^C
~ $

**Comment by TermuxHackz** [comment]
@Swiftness48 kindly check as you might have interrupted the download or check you have a stable internet connection
