### ISSUE TITLE
use --break-system-packages with pip

### ISSUE THREAD

**Issue by midnit3Z0mbi3** [TermuxHackz/X-osint#45]
edit the setup.sh file.

on each pip install entry append "--break-system-packages"

create a venv and activate it

sudo bash setup.sh

install:

cd $HOME
git clone https://github.com/TermuxHackz/X-osint
cd X-osint
nano setup.sh
chmod +x *.sh
python3 -m venv X-osint_venv
source X-osint_venv/bin/activate
 sudo bash setup.sh

**Comment by TermuxHackz** [comment]
Hello @midnit3Z0mbi3 , seems intriguing, I would try to fix such errors, but would ask if you would like to make a pull request

**Comment by midnit3Z0mbi3** [comment]
Hello @TermuxHackz I am still new to Github. I should have done that first. I will do that soon.
