### ISSUE TITLE
Repository just get deleted after the installation

### ISSUE THREAD

**Issue by Nikita656263** [TermuxHackz/X-osint#46]
I just installed X-osint and after rebooting I lost the repository (the command "cd X-osint" does not work and "ls" does not display it). an error is displayed when trying to enter the "xosint" command:

Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 27, in <module>
    from PIL import Image
ModuleNotFoundError: No module named 'PIL'

Help please

**Comment by Nikita656263** [comment]
I forgot to say, I downloaded everything in Termux, suddenly it's important

**Comment by TermuxHackz** [comment]
Hi @Nikita656263 thank you for sharing your experience using X-osint, they’re so many errors with X-osint 😅which wasn’t so in previous months, however these errors would be fixed real soon. Thanks

**Comment by TermuxHackz** [comment]
Hello @Nikita656263 kindly run the code <code>pip install Pillow</code> to install pillow and everything should work as normal
