### ISSUE TITLE
X osint running error

### ISSUE THREAD

**Issue by Travelling-Human** [TermuxHackz/X-osint#50]
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 946, in <module>                                                              root = tk.Tk()
           ^^^^^^^
  File "/data/data/com.termux/files/usr/lib/python3.11/tkinter/__init__.py", line 2345, in __init__
    self.tk = _tkinter.create(screenName, baseName, className, interactive, wantobjects, useTk, sync, use)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
_tkinter.TclError: no display name and no $DISPLAY environment variable

This is what I saw when I tried to run x-osint after the necessary package installation. What should I do

**Comment by Alex8323** [comment]
apt install tk

**Comment by Travelling-Human** [comment]
> apt install tk

Thank you

**Comment by 6oname** [comment]
> > apt install tk
> 
> Thank you
> 
> And what should I do when this happens
> 
> Traceback (most recent call last): File "/data/data/com.termux/files/usr/bin/xosint", line 29, in import tkinter as tk ModuleNotFoundError: No module named 'tkinter'
> 
> I kindly ask for a quick reply

Bro, have you found the answer?

**Comment by Travelling-Human** [comment]
> > > apt install tk
> > 
> > Thank you
> > 
> > And what should I do when this happens
> > 
> > Traceback (most recent call last): File "/data/data/com.termux/files/usr/bin/xosint", line 29, in import tkinter as tk ModuleNotFoundError: No module named 'tkinter'
> > 
> > I kindly ask for a quick reply
> 
> Bro, have you found the answer?

No dude

**Comment by Travelling-Human** [comment]
Thank you
