### ISSUE TITLE
Error at startup

### ISSUE THREAD

**Issue by 6oname** [TermuxHackz/X-osint#54]
![Screenshot_2024-07-23-23-28-44-783_com termux](https://github.com/user-attachments/assets/0c6303f4-d336-4e94-9be5-6f4f0b86a0a5)
![Screenshot_2024-07-23-23-30-14-251_com termux](https://github.com/user-attachments/assets/bfa3e6f0-b3b3-410e-88e1-2fd316a2df05)
What should I do, please help me 😭😭😭

**Comment by TermuxHackz** [comment]
No worries, ill update the script to make sure it works

**Comment by TermuxHackz** [comment]
@6oname The issue you are having has been fixed now with a little update, kindly update Xosint manually to be able to enjoy a bug free OSINT tool, Read [here](https://github.com/TermuxHackz/X-osint?tab=readme-ov-file#how-to-update-manually-for-any-version) on how to update manually

**Comment by 6oname** [comment]
> @6oname The issue you are having has been fixed now with a little update, kindly update Xosint manually to be able to enjoy a bug free OSINT tool, Read [here](https://github.com/TermuxHackz/X-osint?tab=readme-ov-file#how-to-update-manually-for-any-version) on how to update manually

BROOOOOO THANK YOUUUUU

**Comment by TermuxHackz** [comment]
@6oname My pleasure!
