### ISSUE TITLE
Traceback (most recent call last):
  File "/data/data/com.termux/files/usr/bin/xosint", line 29, in <module>
    import tkinter as tk
  File "/data/data/com.termux/files/usr/lib/python3.11/tkinter/__init__.py", line 38, in <module>
    import _tkinter # If this fails your Python may not be configured for Tk
    ^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named '_tkinter'

### ISSUE THREAD

**Issue by yadoter73** [TermuxHackz/X-osint#55]

**Comment by TermuxHackz** [comment]
@yadoter73 kindly upgrade your python package and try to install Tk again (tkinter)

**Comment by TermuxHackz** [comment]
@yadoter73 Ive updated the code now so it should be able to work, kindly read [here](https://github.com/TermuxHackz/X-osint?tab=readme-ov-file#how-to-update-manually-for-any-version) on how to manually update the script
