### ISSUE TITLE
imdb problem

### ISSUE THREAD

**Issue by deados** [TermuxHackz/X-osint#6]
When I launch xosint, there was an error:
$ sudo xosint
Traceback (most recent call last):
  File "/usr/local/bin/xosint", line 22, in <module>
    import imdb
ModuleNotFoundError: No module named 'imdb'

**Comment by TermuxHackz** [comment]
Hello there, please make sure you ran the `bash setup.sh` file as this will install all the necessary requirements needed to run xosint. If it doesn't still work open a new terminal and run <b>pip install imdbpy</b> and then run xosint again. That should fix your error. Thank you

**Comment by deados** [comment]
Ok, that's only permissions' problem. Thank you.

**Comment by TermuxHackz** [comment]
@deados does it work now?, kindly let me know

**Comment by deados** [comment]
Yes, it's working perfectly well!
