### ISSUE TITLE
error when trying to run sudo xosint

### ISSUE THREAD

**Issue by Itwasntme223** [TermuxHackz/X-osint#7]
sudo xosint
Traceback (most recent call last):
  File "/usr/local/bin/xosint", line 11, in <module>
    from googlesearch import search
ModuleNotFoundError: No module named 'googlesearch'

**Comment by TermuxHackz** [comment]
Hi there @Itwasntme223 , sorry for the issue you are experiencing when trying to run xosint, kindly make sure you ran the `bash setup.sh` file as this will install the recommended python packages required to run xosint, it may take some while but when is finished, you won't have any more issues, if that doesn't still work try running the following `pip install google` 
That should help and if it doesn't still work, kindly reach out to me again. Thank you! 

AnonyminHack5

**Comment by kuteriya** [comment]
sir sudo Xosint error
 Traceback (most recent call last):   File "/usr/local/bin/xosint", line 39, in <module>     import update_check ModuleNotFoundError: No module named 'update_check'
