### ISSUE TITLE
issue in termux using xosint

### ISSUE THREAD

**Issue by kabir4562** [TermuxHackz/X-osint#9]
![Screenshot_20230528_232536](https://github.com/TermuxHackz/X-osint/assets/107128684/b4d6e83f-d42b-4adf-8c1a-aca57519529c)
i give you this screenshot for six this issue give me new tool for working in android.

Thank you for give times for us.

**Comment by TermuxHackz** [comment]
Type pip install folium

**Comment by Zarbok786** [comment]
It's because numpy won't build on termux, use `pkg install python-numpy` then `pip install folium` and it should run
